<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "件") %>のエラーがあります。</h2>
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "container">
    <%= form.label :title, id: "title" %>
    <%= form.text_field :title, id: "title" %>
    <%= form.label :limit, id: "limit" %>
    <%= form.datetime_select :limit, id: "limit" %>
    <%= form.label :status, id: "status" %>
    <%= form.select :status, Task.statuses.keys %>
    <%= form.label :priority, id: "priority" %>
    <%= form.select :priority, Task.priorities.keys %>
    <%= form.submit %>
  </div>
<% end %>